### ISSUE TITLE
Kohya_ss native trainer colab broken yesterday. Captured before/ after install log. Jax, Key array. 

### ISSUE THREAD

**Issue by SarahPeterson2854** [kohya-ss/sd-scripts#1641]
Previously the install was broken by jax key array but could be fixed by:
!pip install "jax[cuda12_pip]==0.4.23" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

Any ideas whats broken? Is it because colab updated the default package versions? 

It will kill the colab when you reach start training.
Reproduce:
https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-trainer.ipynb

**Working output:**
Stream
		Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
		Collecting jax==0.4.23 (from jax[cuda12_pip]==0.4.23)
		  Downloading jax-0.4.23-py3-none-any.whl.metadata (24 kB)
		Requirement already satisfied: ml-dtypes>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (0.4.1)
		Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (1.26.4)
		Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (3.3.0)
		Requirement already satisfied: scipy>=1.9 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (1.13.1)
		Collecting jaxlib==0.4.23+cuda12.cudnn89 (from jax[cuda12_pip]==0.4.23)
		  Downloading https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.23%2Bcuda12.cudnn89-cp310-cp310-manylinux2014_x86_64.whl (131.8 MB)
		[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m131.8/131.8 MB[0m [31m8.8 MB/s[0m eta [36m0:00:00[0m
		[?25hCollecting nvidia-cublas-cu12>=12.2.5.6 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cublas_cu12-12.6.1.4-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Collecting nvidia-cuda-cupti-cu12>=12.2.142 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cuda_cupti_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
		Collecting nvidia-cuda-nvcc-cu12>=12.2.140 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cuda_nvcc_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Collecting nvidia-cuda-runtime-cu12>=12.2.140 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cuda_runtime_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Requirement already satisfied: nvidia-cudnn-cu12>=8.9 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12_pip]==0.4.23) (8.9.2.26)
		Collecting nvidia-cufft-cu12>=11.0.8.103 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cufft_cu12-11.2.6.59-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Collecting nvidia-cusolver-cu12>=11.5.2 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cusolver_cu12-11.6.4.69-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
		Collecting nvidia-cusparse-cu12>=12.1.2.141 (from jax[cuda12_pip]==0.4.23)
		  Downloading nvidia_cusparse_cu12-12.5.3.3-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
		Collecting nvidia-nccl-cu12>=2.18.3 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
		Requirement already satisfied: nvidia-nvjitlink-cu12>=12.2 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12_pip]==0.4.23) (12.6.68)
		Downloading jax-0.4.23-py3-none-any.whl (1.7 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m1.7/1.7 MB[0m [31m33.9 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cublas_cu12-12.6.1.4-py3-none-manylinux2014_x86_64.whl (378.9 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m378.9/378.9 MB[0m [31m2.3 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cuda_cupti_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl (8.9 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m8.9/8.9 MB[0m [31m113.5 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cuda_nvcc_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl (21.1 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m21.1/21.1 MB[0m [31m86.4 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cuda_runtime_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl (897 kB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m897.7/897.7 kB[0m [31m50.5 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cufft_cu12-11.2.6.59-py3-none-manylinux2014_x86_64.whl (192.5 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m192.5/192.5 MB[0m [31m5.8 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cusolver_cu12-11.6.4.69-py3-none-manylinux2014_x86_64.whl (130.5 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m130.5/130.5 MB[0m [31m8.6 MB/s[0m eta [36m0:00:00[0m
		[?25hDownloading nvidia_cusparse_cu12-12.5.3.3-py3-none-manylinux2014_x86_64.whl (216.5 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m216.5/216.5 MB[0m [31m3.0 MB/s[0m eta [36m0:00:00[0m
		[?25hUsing cached nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl (199.0 MB)
		Installing collected packages: nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvcc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, jaxlib, jax
		  Attempting uninstall: nvidia-nccl-cu12
		    Found existing installation: nvidia-nccl-cu12 2.18.1
		    Uninstalling nvidia-nccl-cu12-2.18.1:
		      Successfully uninstalled nvidia-nccl-cu12-2.18.1
		  Attempting uninstall: nvidia-cusparse-cu12
		    Found existing installation: nvidia-cusparse-cu12 12.1.0.106
		    Uninstalling nvidia-cusparse-cu12-12.1.0.106:
		      Successfully uninstalled nvidia-cusparse-cu12-12.1.0.106
		  Attempting uninstall: nvidia-cufft-cu12
		    Found existing installation: nvidia-cufft-cu12 11.0.2.54
		    Uninstalling nvidia-cufft-cu12-11.0.2.54:
		      Successfully uninstalled nvidia-cufft-cu12-11.0.2.54
		  Attempting uninstall: nvidia-cuda-runtime-cu12
		    Found existing installation: nvidia-cuda-runtime-cu12 12.1.105
		    Uninstalling nvidia-cuda-runtime-cu12-12.1.105:
		      Successfully uninstalled nvidia-cuda-runtime-cu12-12.1.105
		  Attempting uninstall: nvidia-cuda-cupti-cu12
		    Found existing installation: nvidia-cuda-cupti-cu12 12.1.105
		    Uninstalling nvidia-cuda-cupti-cu12-12.1.105:
		      Successfully uninstalled nvidia-cuda-cupti-cu12-12.1.105
		  Attempting uninstall: nvidia-cublas-cu12
		    Found existing installation: nvidia-cublas-cu12 12.1.3.1
		    Uninstalling nvidia-cublas-cu12-12.1.3.1:
		      Successfully uninstalled nvidia-cublas-cu12-12.1.3.1
		  Attempting uninstall: nvidia-cusolver-cu12
		    Found existing installation: nvidia-cusolver-cu12 11.4.5.107
		    Uninstalling nvidia-cusolver-cu12-11.4.5.107:
		      Successfully uninstalled nvidia-cusolver-cu12-11.4.5.107
		  Attempting uninstall: jaxlib
		    Found existing installation: jaxlib 0.4.26+cuda12.cudnn89
		    Uninstalling jaxlib-0.4.26+cuda12.cudnn89:
		      Successfully uninstalled jaxlib-0.4.26+cuda12.cudnn89
		  Attempting uninstall: jax
		    Found existing installation: jax 0.4.26
		    Uninstalling jax-0.4.26:
		      Successfully uninstalled jax-0.4.26
		[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
		orbax-checkpoint 0.6.4 requires jax>=0.4.26, but you have jax 0.4.23 which is incompatible.
		torch 2.1.0 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.6.1.4 which is incompatible.
		torch 2.1.0 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.6.68 which is incompatible.
		torch 2.1.0 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.6.68 which is incompatible.
		torch 2.1.0 requires nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.6.59 which is incompatible.
		torch 2.1.0 requires nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.4.69 which is incompatible.
		torch 2.1.0 requires nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.3.3 which is incompatible.
		torch 2.1.0 requires nvidia-nccl-cu12==2.18.1; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nccl-cu12 2.23.4 which is incompatible.
		torchaudio 2.4.1+cu121 requires torch==2.4.1, but you have torch 2.1.0 which is incompatible.[0m[31m
		[0mSuccessfully installed jax-0.4.23 jaxlib-0.4.23+cuda12.cudnn89 nvidia-cublas-cu12-12.6.1.4 nvidia-cuda-cupti-cu12-12.6.68 nvidia-cuda-nvcc-cu12-12.6.68 nvidia-cuda-runtime-cu12-12.6.68 nvidia-cufft-cu12-11.2.6.59 nvidia-cusolver-cu12-11.6.4.69 nvidia-cusparse-cu12-12.5.3.3 nvidia-nccl-cu12-2.23.4

**Broken output**
Stream
		Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
		Collecting jax==0.4.23 (from jax[cuda12_pip]==0.4.23)
		  Downloading jax-0.4.23-py3-none-any.whl.metadata (24 kB)
		Requirement already satisfied: ml-dtypes>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (0.4.1)
		Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (1.26.4)
		Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (3.3.0)
		Requirement already satisfied: scipy>=1.9 in /usr/local/lib/python3.10/dist-packages (from jax==0.4.23->jax[cuda12_pip]==0.4.23) (1.13.1)
		Collecting jaxlib==0.4.23+cuda12.cudnn89 (from jax[cuda12_pip]==0.4.23)
		  Downloading https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.23%2Bcuda12.cudnn89-cp310-cp310-manylinux2014_x86_64.whl (131.8 MB)
		[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m131.8/131.8 MB[0m [31m7.9 MB/s[0m eta [36m0:00:00[0m
		[?25hCollecting nvidia-cublas-cu12>=12.2.5.6 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_cublas_cu12-12.6.1.4-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Collecting nvidia-cuda-cupti-cu12>=12.2.142 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_cuda_cupti_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
		Requirement already satisfied: nvidia-cuda-nvcc-cu12>=12.2.140 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12_pip]==0.4.23) (12.6.68)
		Collecting nvidia-cuda-runtime-cu12>=12.2.140 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_cuda_runtime_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Requirement already satisfied: nvidia-cudnn-cu12>=8.9 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12_pip]==0.4.23) (8.9.2.26)
		Collecting nvidia-cufft-cu12>=11.0.8.103 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_cufft_cu12-11.2.6.59-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
		Collecting nvidia-cusolver-cu12>=11.5.2 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_cusolver_cu12-11.6.4.69-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
		Collecting nvidia-cusparse-cu12>=12.1.2.141 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_cusparse_cu12-12.5.3.3-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
		Collecting nvidia-nccl-cu12>=2.18.3 (from jax[cuda12_pip]==0.4.23)
		  Using cached nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
		Requirement already satisfied: nvidia-nvjitlink-cu12>=12.2 in /usr/local/lib/python3.10/dist-packages (from jax[cuda12_pip]==0.4.23) (12.6.68)
		Downloading jax-0.4.23-py3-none-any.whl (1.7 MB)
		[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m1.7/1.7 MB[0m [31m29.0 MB/s[0m eta [36m0:00:00[0m
		[?25hUsing cached nvidia_cublas_cu12-12.6.1.4-py3-none-manylinux2014_x86_64.whl (378.9 MB)
		Using cached nvidia_cuda_cupti_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl (8.9 MB)
		Using cached nvidia_cuda_runtime_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl (897 kB)
		Using cached nvidia_cufft_cu12-11.2.6.59-py3-none-manylinux2014_x86_64.whl (192.5 MB)
		Using cached nvidia_cusolver_cu12-11.6.4.69-py3-none-manylinux2014_x86_64.whl (130.5 MB)
		Using cached nvidia_cusparse_cu12-12.5.3.3-py3-none-manylinux2014_x86_64.whl (216.5 MB)
		Using cached nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl (199.0 MB)
		Installing collected packages: nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, jaxlib, jax
		  Attempting uninstall: nvidia-nccl-cu12
		    Found existing installation: nvidia-nccl-cu12 2.18.1
		    Uninstalling nvidia-nccl-cu12-2.18.1:
		      Successfully uninstalled nvidia-nccl-cu12-2.18.1
		  Attempting uninstall: nvidia-cusparse-cu12
		    Found existing installation: nvidia-cusparse-cu12 12.1.0.106
		    Uninstalling nvidia-cusparse-cu12-12.1.0.106:
		      Successfully uninstalled nvidia-cusparse-cu12-12.1.0.106
		  Attempting uninstall: nvidia-cufft-cu12
		    Found existing installation: nvidia-cufft-cu12 11.0.2.54
		    Uninstalling nvidia-cufft-cu12-11.0.2.54:
		      Successfully uninstalled nvidia-cufft-cu12-11.0.2.54
		  Attempting uninstall: nvidia-cuda-runtime-cu12
		    Found existing installation: nvidia-cuda-runtime-cu12 12.1.105
		    Uninstalling nvidia-cuda-runtime-cu12-12.1.105:
		      Successfully uninstalled nvidia-cuda-runtime-cu12-12.1.105
		  Attempting uninstall: nvidia-cuda-cupti-cu12
		    Found existing installation: nvidia-cuda-cupti-cu12 12.1.105
		    Uninstalling nvidia-cuda-cupti-cu12-12.1.105:
		      Successfully uninstalled nvidia-cuda-cupti-cu12-12.1.105
		  Attempting uninstall: nvidia-cublas-cu12
		    Found existing installation: nvidia-cublas-cu12 12.1.3.1
		    Uninstalling nvidia-cublas-cu12-12.1.3.1:
		      Successfully uninstalled nvidia-cublas-cu12-12.1.3.1
		  Attempting uninstall: nvidia-cusolver-cu12
		    Found existing installation: nvidia-cusolver-cu12 11.4.5.107
		    Uninstalling nvidia-cusolver-cu12-11.4.5.107:
		      Successfully uninstalled nvidia-cusolver-cu12-11.4.5.107
		  Attempting uninstall: jaxlib
		    Found existing installation: jaxlib 0.4.33
		    Uninstalling jaxlib-0.4.33:
		      Successfully uninstalled jaxlib-0.4.33
		  Attempting uninstall: jax
		    Found existing installation: jax 0.4.33
		    Uninstalling jax-0.4.33:
		      Successfully uninstalled jax-0.4.33
		[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
		flax 0.8.5 requires jax>=0.4.27, but you have jax 0.4.23 which is incompatible.
		optax 0.2.3 requires jax>=0.4.27, but you have jax 0.4.23 which is incompatible.
		optax 0.2.3 requires jaxlib>=0.4.27, but you have jaxlib 0.4.23+cuda12.cudnn89 which is incompatible.
		orbax-checkpoint 0.6.4 requires jax>=0.4.26, but you have jax 0.4.23 which is incompatible.
		torch 2.1.0 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.6.1.4 which is incompatible.
		torch 2.1.0 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.6.68 which is incompatible.
		torch 2.1.0 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.6.68 which is incompatible.
		torch 2.1.0 requires nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.6.59 which is incompatible.
		torch 2.1.0 requires nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.4.69 which is incompatible.
		torch 2.1.0 requires nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.3.3 which is incompatible.
		torch 2.1.0 requires nvidia-nccl-cu12==2.18.1; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nccl-cu12 2.23.4 which is incompatible.
		torchaudio 2.4.1+cu121 requires torch==2.4.1, but you have torch 2.1.0 which is incompatible.[0m[31m
		[0mSuccessfully installed jax-0.4.23 jaxlib-0.4.23+cuda12.cudnn89 nvidia-cublas-cu12-12.6.1.4 nvidia-cuda-cupti-cu12-12.6.68 nvidia-cuda-runtime-cu12-12.6.68 nvidia-cufft-cu12-11.2.6.59 nvidia-cusolver-cu12-11.6.4.69 nvidia-cusparse-cu12-12.5.3.3 nvidia-nccl-cu12-2.23.4

**Comment by upright2003** [comment]
https://stackoverflow.com/questions/79023291/kohya-ss-colab-fine-tune-jax-error-torch-compatibility

**Comment by xjdeng** [comment]
Hello? Anyone?

What I've tried so far:

- Restarting the instance after installing Jax 0.4.23.  It seems the latest version gets imported even if you install this one unless you restart.  But then, I still get an error when i run the following:

'import os
os.chdir(finetune_dir)
try:
    import logging
    logging.basicConfig(
        level=logging.DEBUG,  # Change this to logging.INFO or logging.WARNING to reduce verbosity
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.StreamHandler(),  # This ensures logs are printed to the console
            logging.FileHandler("log.txt", mode='w')  # This writes logs to a file
        ]
    )
    import library.train_util as train_util
    print("train_util imported successfully")
except Exception as e:
    print(f"Error importing train_util: {e}")'

But it ends up crashing.

**Comment by SarahPeterson2854** [comment]
* update, 
* Colabs latest update has broken the working script + jax fix. You can test this by reverting to the fallback version > command pallete >use fall back. Then it works. You can also do this to capture all the versions with pip show, not how I did it in the OP. Trying to force install these or pip-sync to the previous working environment's packages doesn't work. I wonder if its going to be necessary to make updates to use a later version of jax...

**Comment by SarahPeterson2854** [comment]
Here is what they explicitly changed: https://colab.research.google.com/notebooks/relnotes.ipynb

Python package upgrades

accelerate 0.32.1 -> 0.34.2
arviz 0.18.0 -> 0.19
autograd 1.6.2 -> 1.7.0
bigframes 1.14.0 -> 1.18.0
dask 2024.7.1 -> 2024.8.0
distributed 2024.7.1 -> 2024.8.0
duckdb 0.10.3 -> 1.1.0
earthengine-api 0.1.416 -> 1.0.0
flax 0.8.4 -> 0.8.5
gdown 5.1.0 -> 5.2.0
geemap 0.33.1 -> 0.34.3
geopandas 0.14.4 -> 1.0.1
google-cloud-aiplatform 1.59.0 -> 1.67.1
google-cloud-bigquery-storage 2.25.0 -> 2.26.0
holidays 0.54 -> 0.57
huggingface-hub 0.23.5 -> 0.24.7
ibis-framework 8.0.0 -> 9.2.0
jax 0.4.26 -> 0.4.33
jaxlib 0.4.26 -> 0.4.33
kagglehub 0.2.9 -> 0.3.0
lightgbm 4.4.0 -> 4.5.0
matplotlib-venn 0.11.10 -> 1.1.1
mizani 0.9.3 -> 0.11.4
Pillow 9.4.0 -> 10.4.0
plotly 5.15.0 -> 5.24.1
plotnine 0.12.4 -> 0.13.6
polars 0.20.2 -> 1.6.0
progressbar2 4.2.0 -> 4.5.0
PyDrive2 1.6.3 -> 1.20.0
pymc 5.10.4 -> 5.16.2
pytensor 2.18.6 -> 2.25.4
scikit-image 0.23.2 -> 0.24.0
scikit-learn 1.3.2 -> 1.5.2
torch 2.3.1 -> 2.4.1
torchaudio 2.3.1 -> 2.4.1
torchvision 0.18.1 -> 0.19.1
transformers 4.42.4 -> 4.44.2
urllib3 2.0.7 -> 2.2.3
xarray 2024.6.0 -> 2024.9.0
Python package inclusions

bigquery-magics 0.2.0

**Comment by SarahPeterson2854** [comment]
fallback runtime has now been disabled and kohya_ss colab is completely broken

**Comment by SarahPeterson2854** [comment]
working patch for finetune post colab updates 25th Nov 2024 but slower is: 
switch repo_url = "https://github.com/xjdeng/sd-scripts"

and then also !wget -O /content/kohya-trainer/finetune/merge_all_to_metadata.py https://raw.githubusercontent.com/Linaqruf/kohya-trainer/refs/heads/main/finetune/merge_all_to_metadata.py

and finally 

def comment_out_register_fake(file_path, line_number):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    if line_number <= len(lines):
        # Comment out the offending line
        lines[line_number - 1] = '# ' + lines[line_number - 1]

        # Write the lines back to the file
        with open(file_path, 'w') as file:
            file.writelines(lines)
        print(f"Line {line_number} commented out successfully.")
    else:
        print(f"Line {line_number} does not exist in the file.")

# Path to the _meta_registrations.py file
file_path = '/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py'

# Line number where the register_fake is located (line 163 in your case)
line_number = 163

# Call the function to comment out the line
comment_out_register_fake(file_path, line_number)


/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:211: FutureWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:344: FutureWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Loading settings from /content/fine_tune/config/config_file.toml...
/content/fine_tune/config/config_file
prepare tokenizer
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1150: FutureWarning: resume_download is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use force_download=True.
  warnings.warn(
tokenizer_config.json: 100% 905/905 [00:00<00:00, 4.89MB/s]
vocab.json: 100% 961k/961k [00:00<00:00, 2.00MB/s]
merges.txt: 100% 525k/525k [00:00<00:00, 2.37MB/s]
special_tokens_map.json: 100% 389/389 [00:00<00:00, 2.41MB/s]
tokenizer.json: 100% 2.22M/2.22M [00:01<00:00, 1.80MB/s]
update token length: 225
loading existing metadata: /content/fine_tune/meta_lat.json
metadata has bucket info, enable bucketing / メタデータにbucket情報があるためbucketを有効にします
using bucket info in metadata / メタデータ内のbucket情報を使います
[Dataset 0]
  batch_size: 1
  resolution: (768, 512)
  enable_bucket: True
  network_multiplier: 1.0
  min_bucket_reso: None
  max_bucket_reso: None
  bucket_reso_steps: None
  bucket_no_upscale: None

  [Subset 0 of Dataset 0]
    image_dir: "/content/train_data"
    image_count: 212
    num_repeats: 1
    shuffle_caption: True
    keep_tokens: 1
    keep_tokens_separator: 
    secondary_separator: None
    enable_wildcard: False
    caption_dropout_rate: 0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    metadata_file: /content/fine_tune/meta_lat.json


[Dataset 0]
loading image sizes.
100% 212/212 [00:00<00:00, 1165389.84it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 768), count: 36
bucket 1: resolution (576, 576), count: 62
bucket 2: resolution (768, 512), count: 114
mean ar error (without repeats): 0.0
prepare accelerator
accelerator device: cuda
loading model for process 0/1
load StableDiffusion checkpoint: /content/drive/MyDrive/fine_tune/output/stdggyFT15c.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
load VAE: /content/vae/stablediffusion.vae.pt
/content/kohya-trainer/library/model_util.py:1287: FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  vae_model = load_file(vae_id, "cuda") if is_safetensors(vae_id) else torch.load(vae_id, map_location="cpu")
additional VAE loaded
Disable Diffusers' xformers
Enable xformers for U-Net
prepare optimizer, data loader etc.
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num examples / サンプル数: 212
  num batches per epoch / 1epochのバッチ数: 212
  num epochs / epoch数: 24
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 5000
steps:   0% 0/5000 [00:00<?, ?it/s]
epoch 1/24
steps:   0% 13/5000 [00:37<3:58:27,  2.87s/it, avr_loss=0.103]

**Comment by xjdeng** [comment]
Thanks @SarahPeterson2854 ,

Alternatively, I've refactored @Linaqruf 's notebook and used his training methodology which seems to take longer to set up but seems to be faster.  You can find it here: https://github.com/xjdeng/sd-colab-notebooks

**Comment by SarahPeterson2854** [comment]
> Thanks @SarahPeterson2854 ,
> 
> Alternatively, I've refactored @Linaqruf 's notebook and used his training methodology which seems to take longer to set up but seems to be faster. You can find it here: https://github.com/xjdeng/sd-colab-notebooks

Thanks 100x.

Also, I was giving instructions for fully fine tuning sd1.5 not "lora". The notebook you refactored is just for the lora. Any idea why its slower? I have 2.74s/it with your fork whereas prior to the colab update (and using fallback runtime) 1.67. 

also here is the fix for skipping computing the latents if you already have them in the train data folder: under config add "skip_existing": skip_existing,
and above that set skip_existing = True. It works,

**Comment by xjdeng** [comment]
@SarahPeterson2854 Oh, I've pretty much stopped fully fine tuning and just fine tune a LoRA to attach to a main model (otherwise, I often get extremely garbled results)..  maybe it's my dataset but that's been the case with both Linaqruf's old trainer as well as other reputable ones like EveryDream2.  I might take another look at fine tuning again, especially now that the Prodigy optimizer is supported (which I've hard coded into my notebook to simply the learning rate selection.)
