### ISSUE TITLE
How do I clear VRAM after saving the latent cache and prevent OOM ?

### ISSUE THREAD

**Issue by muooon** [kohya-ss/sd-scripts#2006]
latent cache 保存後の VRAM クリアと OOM 防止について教えてください。

Kohya sd-script を RTX3060-12G で使っています。
数百枚規模以上のデータセットを 解像度 1024pix 以上の resolution と latent chache 作成する設定で学習を開始させますと、ある程度まで latent cache を保存したところで OOM となり、処理中止、または PC-Main-Memory へ溢れ処理速度を落としてゆっくり継続することになります。やがて chache をすべて保存し終えると Vram は解放され、次のステップへ進み Triton 云々が警告され、そして学習そのものが開始されます。

ここで、latent cache を保存毎や、または Vram を監視しながら一定の使用率に達した場合に Vram 解放を行うことで OOM を防止し処理速度を保つことはできないのか？ と素人考えで思います。
または学習開始前までの latent cache 保存だけ行うモードで、chache 保存毎に Vram を解放し快適な速度で cache 作成のみを実行してくれないかな、などと思う次第です。

以前に２万枚規模のデータセットで学習開始をしたところ、latent chache の作成だけで30時間超となり、静かに我慢して待ち続けたこともあります。latent cache を保存する、というアイデアのお陰で RTX3060 でも満足な学習を行えることはありがたいことで感謝しています。が、もうひとつ進化して頂けると、さらに学習への敷居が下がるかと思います。

また次世代アーキテクチャは軒並み 大容量 Vram を必要としていますが、もし latent cache を事前に素早く作成し保存できれば、これは学習を促進することに貢献するだろうとも思います。もし可能であればこれについてご検討ください。よろしくお願いします。

How do I clear VRAM after saving the latent cache and prevent OOM?

I am using Kohya sd-script with RTX3060-12G.
If you start learning with a dataset of several hundred images or more, a resolution of 1024pix or more, and settings that create a latent cache, OOM will occur after saving a certain amount of latent cache, and the process will be stopped, or it will overflow into PC-Main-Memory and continue slowly with reduced processing speed. Eventually, when all the caches have been saved, VRAM will be released, the process will proceed to the next step, a warning about Triton will be displayed, and the learning itself will begin.

So, I wonder, as an amateur, if we could prevent OOM and maintain processing speed by monitoring the latent cache every time it is saved, or by releasing the VRAM when a certain usage rate is reached while monitoring the VRAM?
Or I wonder if it would be possible to set it to a mode that only saves the latent cache before learning begins, freeing up VRAM each time a cache is saved and only creating the cache at a comfortable speed.

Previously, when I started training with a dataset of 20,000 images, it took more than 30 hours just to create the latent cache, and I patiently waited patiently. Thanks to the idea of ​​saving the latent cache, I am grateful that I can train satisfactorily even with an RTX3060. However, if it could be further improved, I think the barrier to learning would be lowered even further.

Also, next-generation architectures across the board require large VRAMs, so if we could create and store a latent cache quickly in advance, I think this would help accelerate learning. Please consider this if possible. Thank you.

**Comment by muooon** [comment]
解決済み

--highvram を使っていたのが間違いでした。これを外して学習開始すれば vram は溢れずに latent cache を作り続けることができました。(詳細を記述しているマニュアルを読んで解決しました)

kohya-script を開発する皆さまにお詫びし訂正します。そしてこの issue を"解決済み"で終了します。お騒がせしました。どうもありがとうございました。

Solved...

I was using highvram by mistake. When I removed it and started learning, vram did not overflow and I was able to continue creating latent cache. (I solved it by reading the manual which describes the details)

I apologize to all developers of kohya-script and will correct the issue. I will close this issue as "solved". Thank you very much for your time.
