### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [kohya-ss/sd-scripts#44]
Error no kernel image is available for execution on the device at line 89 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\Users\Siddhesh\Desktop\kohya_ss\venv\Scripts\accelerate.exe_main.py", line 7, in
File "C:\Users\Siddhesh\Desktop\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
args.func(args)
File "C:\Users\Siddhesh\Desktop\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
simple_launcher(args)
File "C:\Users\Siddhesh\Desktop\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\Users\Siddhesh\Desktop\kohya_ss\venv\Scripts\python.exe', 'train_network.py', '--cache_latents', '--enable_bucket', '--use_8bit_adam', '--xformers', '--pretrained_model_name_or_path=C:/Users/Siddhesh/Desktop/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt', '--train_data_dir=C:/Users/Siddhesh/Desktop/test\img', '--resolution=512,512', '--output_dir=C:/Users/Siddhesh/Desktop/test\model', '--train_batch_size=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400', '--use_8bit_adam', '--xformers', '--mixed_precision=fp16', '--save_every_n_epochs=1', '--seed=1234', '--save_precision=fp16', '--logging_dir=C:/Users/Siddhesh/Desktop/test\log', '--network_module=networks.lora', '--text_encoder_lr=1e-06', '--unet_lr=0.0001', '--network_dim=4']' returned non-zero exit status 1.

(venv) PS C:\Users\Siddhesh\Desktop\kohya_ss> python
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec 6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import torch
import sys
print('A', sys.version)
A 3.10.9 (tags/v3.10.9:1dd9be6, Dec 6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
print('B', torch.version)
B 1.12.1+cu116
print('C', torch.cuda.is_available())
C True
print('D', torch.backends.cudnn.enabled)
D True
device = torch.device('cuda')
print('E', torch.cuda.get_device_properties(device))
E _CudaDeviceProperties(name='NVIDIA GeForce GTX 1060 6GB', major=6, minor=1, total_memory=6143MB, multi_processor_count=10)
print('F', torch.tensor([1.0, 2.0]).cuda())
F tensor([1., 2.], device='cuda:0')

EDIT: Error no kernel image is available for execution on the device at line 89 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

^^ The bold part must be the error because I have no D:\ drive on my system!

**Comment by JSarvise** [comment]
Getting a similar error

Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\friky\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\friky\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\friky\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\friky\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\friky\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\friky\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\friky\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--network_module=networks.lora', '--pretrained_model_name_or_path=D:\\descargas\\novelaileak\\stableckpt\\animefull-final-pruned\\model.ckpt', '--train_data_dir=D:\\image\\img', '--reg_data_dir=D:\\image\\reg', '--output_dir=D:\\image\\model', '--caption_extension=.txt', '--shuffle_caption', '--prior_loss_weight=1', '--resolution=512', '--enable_bucket', '--min_bucket_reso=320', '--max_bucket_reso=960', '--train_batch_size=1', '--learning_rate=0.0001', '--max_train_steps=4720', '--mixed_precision=fp16', '--save_precision=fp16', '--use_8bit_adam', '--xformers', '--save_every_n_epochs=3', '--save_model_as=safetensors', '--clip_skip=2', '--seed=23', '--network_dim=128', '--max_token_length=150', '--cache_latents', '--lr_scheduler=cosine_with_restarts']' returned non-zero exit status 1.

**Comment by JSarvise** [comment]
I'll try this when i get home but apparently removing 8bitadam from the launch parameters on my training script also fixed the issue no idea why

**Comment by geocine** [comment]
> I'll try this when i get home but apparently removing 8bitadam from the launch parameters on my training script also fixed the issue no idea why

Because `bitsandbytes` the one being used for 8 bit optimization

**Comment by lolxdmainkaisemaanlu** [comment]
> Hi, according to the issue in bitsandbytes repo, different versions of CUDA seem to cause this error. [TimDettmers/bitsandbytes#91](https://github.com/TimDettmers/bitsandbytes/issues/91)
> 
> If you installed CUDA 12, please uninstall it and install CUDA 11.x. The 11.6 might be better because PyTorch supports the verison.

I had CUDA 12 previously but I uninstalled it, installed CUDA 11.6 and then restarted and shutdown multiple times and yet I keep getting the same error. I'm now starting to wonder if your code utilizes LLM.int8() along with 8bitoptimizer, because it requires Turing or Ampere GPUs. I have a GTX 1060.

**Comment by lolxdmainkaisemaanlu** [comment]
> This repo seems to have another version of `libbitsandbytes_cuda*.dll`. I'm not sure but the dll might work on GTX 1060. https://github.com/james-things/bitsandbytes-prebuilt-all_arch
> 
> Copy dll and modify `main.py` according to the instructions on the repo. dll will be at `venv\Lib\site-packages\bitsandbytes`, and main.py will be at `venv\Lib\site-packages\bitsandbytes\cuda_setup`.

THANK YOU!!!! This worked! I am not a coder as such and I spent HOURS trying to to understand stuff and fix this.
