### ISSUE TITLE
 CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by jokerJ78** [kohya-ss/sd-scripts#873]
### **1. I experienced this error since i tried to train the Lora myself.** 
<img width="885" alt="train01" src="https://github.com/kohya-ss/sd-scripts/assets/42563859/540cc35c-63c8-4322-9b4a-78c17b3e1f67">
<img width="888" alt="train02" src="https://github.com/kohya-ss/sd-scripts/assets/42563859/c2b9f9ec-8716-43e0-b190-30338f325a6e">

**### 2.To solve this issue, I tried to reinstall the cuda V11.8 and made sure it matching with pytorch**
<img width="338" alt="nvcc" src="https://github.com/kohya-ss/sd-scripts/assets/42563859/9c00ef0c-29e3-4757-9069-d2debb8d98d6">
<img width="409" alt="torch_cuda" src="https://github.com/kohya-ss/sd-scripts/assets/42563859/c56c7179-2a39-4a73-b4e1-ff5b07b53606">

### **3.Also tried the solution provided by bitsandbytes**
<img width="910" alt="byte01" src="https://github.com/kohya-ss/sd-scripts/assets/42563859/ac351dc9-142a-49d5-8112-f07351fe3372">

4.Adding cuda path variable method is also proved useless
Any idea to solve this tricky issue?

**Comment by BrentWilkins** [comment]
For what it's worth I'm having issues with the exact same versions as you:

```shell
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

```python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.1+cu118'
>>> torch.cuda.is_available()
/home/.../venv/lib/python3.10/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False

```

**Comment by BrentWilkins** [comment]
@jokerJ78 I’m sure our problems are slightly different, but here is what worked for me. I ran `dkms status` and the Dynamic Kernel Model Support program told me that there was something wrong with the versions of parts that “I built” and that I got as binaries.
Earlier I had been installing every Nvidia library from their site with `dpkg -i`. At some point I installed one of the many and my system built the kernel modules. The binary ones must have been from the proprietary driver installer software or one of the many packages I manually installed.
Anyway… what ultimately fixed it for me was these two commands. Obviously the the `- k` part needs to match your kernel version `uname -a` will have it somewhere.

```shell
sudo dkms remove -m nvidia -v 535.104.12 -k 6.2.0-34-generic
sudo dkms install -m nvidia -v 535.104.12 -k 6.2.0-34-generic
```

After that the error shown with `dkms status` was gone, and `nvidia-smi` ran!

@kohya-ss thanks for your great tool!
