### ISSUE TITLE
Watchdog caught collective operation timeout - over 30 min during caching latents 

### ISSUE THREAD

**Issue by FurkanGozukara** [kohya-ss/sd-scripts#971]
When caching taking over 30 minutes it time outs. I wonder if this is Kohya related

The message is from Kaggle notebook

```
caching latents.
checking cache validity...
100%|███████████████████████████████████| 1818/1818 [00:00<00:00, 237679.84it/s]
[Dataset 0]
caching latents.
checking cache validity...
100%|████████████████████████████████████| 1818/1818 [00:00<00:00, 68495.35it/s]
caching latents...
 87%|█████████████████████████████████▉     | 1582/1818 [30:02<04:26,  1.13s/it][E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802130 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802130 milliseconds before timing out.
 87%|█████████████████████████████████▉     | 1583/1818 [30:03<04:26,  1.13s/it]Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
./sdxl_train.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-26_04:42:03
  host      : b7sssssssb
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 1252)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1252
=====================================================
```

**Comment by storuky** [comment]
Check [here](https://github.com/kohya-ss/sd-scripts/blob/0908c5414dadfe2185669e2d657d542161647b79/library/train_util.py#L2875)
If you don't pass `ddp_timeout` it will use default accelerate timeout which is 30 minutes. So just pass something like `--ddp_timeout='100000'` (it's in minutes).

**Comment by FurkanGozukara** [comment]
> Check [here](https://github.com/kohya-ss/sd-scripts/blob/0908c5414dadfe2185669e2d657d542161647b79/library/train_util.py#L2875) If you don't pass `ddp_timeout` it will use default accelerate timeout which is 30 minutes. So just pass something like `--ddp_timeout='100000'` (it's in minutes).

awesome will update notebook for this

**Comment by FurkanGozukara** [comment]
> In addition, I think you might cache the latents to disk in advance with `tools/cache_latents.py`.

I tested this and it works

I am using Kohya GUI

updated my Kaggle notebook config file

![image](https://github.com/kohya-ss/sd-scripts/assets/19240467/0609895f-a12a-4ec2-9439-a0839db6671d)


[**How To Do Stable Diffusion XL (SDXL) DreamBooth Training For Free - Utilizing Kaggle - Easy Tutorial**](https://youtu.be/16-b1AjvyBE)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/JU3U2Kk6IdVxx1-hfNkrA.png)](https://youtu.be/16-b1AjvyBE)
